### ISSUE TITLE
We are looking for new maintainers and contributors

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.kubevirt#27]
##### SUMMARY
This collection is a part of Ansible package and is looking for new maintainers and contributors.

To learn how to contribute to the collection and how to maintain it / become a maintainer, refer to the [Contributing guidelines](https://github.com/ansible/community-docs/blob/main/contributing.rst), which also includes the [Quick-start guide](https://github.com/ansible/community-docs/blob/main/create_pr_quick_start_guide.rst), and the [Maintainer guidelines](https://github.com/ansible/community-docs/blob/main/maintaining.rst).

If you are interested in becoming a maintainer, feel free to respond here!

**Comment by Andersson007** [comment]
cc @snecklifter how about becoming a maintainer? If yes, please contact me on aklychko at redhat dot com

**Comment by Andersson007** [comment]
I'm happy to announce that @snecklifter has become a maintainer and congratulate him on this!
Thank you for your interest in looking after such an important collection!

**Comment by Andersson007** [comment]
I'm happy to announce that @snecklifter has become a maintainer and congratulate him on this!
Thank you for your interest in looking after such an important collection!

**Comment by mnecas** [comment]
@Andersson007 if you are still looking for another maintainer I'm opened to it.

**Comment by snecklifter** [comment]
@mnecas would be great to have you, you may recall I also did some stuff for the ovirt modules. :)

**Comment by mnecas** [comment]
Yes was great working with you!

**Comment by Andersson007** [comment]
@mnecas great, thanks for your interest! I'll contact you via email soon!
@snecklifter @mnecas and that's great that you know each other!

**Comment by Andersson007** [comment]
@mnecas please check your email, there should be an invite to the collection. Thank you and my congratulations!:)
Also I've just sent you an email with some basic points on the topic and several links.

**Comment by jseguillon** [comment]
Hi @Andersson007 
Thanks for your reply in #25 

Because I use this collections for my molecule kubevirt driver (https://github.com/jseguillon/molecule-kubevirt)  I am indeed interrested in its maintenance. 

Please note I've never been a maintainer in OSS community. May need some help to do a good job :smiley:

**Comment by Andersson007** [comment]
hi @jseguillon
Thank you for your interest!

There were a couple of attempts to fix the compatibility with dependencies, for example, the latest https://github.com/ansible-collections/community.kubevirt/pull/34.

The problem is also described by @felixfontein in the [removal process issue](https://github.com/ansible-collections/overview/pull/201).

We'll stop the removal process if the issue is fixed and, after that, someone will promise to continue to maintain the collection at some level (we'll adjust their permission to "maintainer" in the repo).
We have a [Quick start dev guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html) which will help set up dev environment and submit a PR quickly. Please take a look.
When there's the PR fixing the issue, we'll review it.

If you have any questions, feel free to ask. We'd love to help:)
Thank you!

**Comment by Andersson007** [comment]
@jseguillon also there's no super rush with this, take your time:)
Even if it gets excluded, there will probably be a simplified way for such `previously-included` collections to get back, though the exclusion is the matter of months anyway.

**Comment by jseguillon** [comment]
Thanks for informations @Andersson007

It is like an "emergency" from my own point of view. Since I'm looking for releasing a kind of stable version, I now have to make a decision: keep using this collection or switch to classic core.k8s tasks.

Would not like to release a piece of software that would require deprecated dependency :/ 

Lets continue on #34 and see if I can help

**Comment by snecklifter** [comment]
@jseguillon thanks for taking a look and sorry this has been neglected. Unfortunately I'm only able to intermittently take a look at things and getting my head around the release process was a bridge too far.

**Comment by Andersson007** [comment]
FYI https://github.com/ansible-collections/community.kubevirt/issues/43 very important, it's going to be removed from the package
